NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc
acme_test:
    type: rest
    resource: "@AcmeDemoBundle/Resources/config/route_test.yml"
    prefix : /api